version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
      - db
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    networks:
      - fpinnova-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 3

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=fpinnova
      - DB_PASSWORD=fpinnova_secure_pass
      - DB_NAME=fpinnova
      - JWT_SECRET=your_secure_jwt_secret_key_here
    volumes:
      - ./uploads:/app/uploads
    networks:
      - fpinnova-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_secure_pass
      - MYSQL_DATABASE=fpinnova
      - MYSQL_USER=fpinnova
      - MYSQL_PASSWORD=fpinnova_secure_pass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fpinnova-network
    command: 
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--max_allowed_packet=128M'
      - '--wait_timeout=28800'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fpinnova", "-pfpinnova_secure_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
    driver: local

networks:
  fpinnova-network:
    driver: bridge